import { NavLink } from "react-router-dom";
import logoImg from "../assets/images/logo.jpg"; /* --- OpenAI (2026),	Generated by the author using ChatGPT , (Accessed: 7 February 2026)*/

/* --- Main navigation links used across the website --- */
const navigationLinks = [
  { path: "/choose", label: "Choose Box" },
  { path: "/mix", label: "Mix Flavours" },
  { path: "/about", label: "About" },
  { path: "/contact", label: "Contact" },
];

/* --- Applies active styling to the current page link --- */
const getNavLinkClass = ({ isActive }) =>
  isActive ? "nav-link active" : "nav-link";

function Navbar({ basketCount }) {
  return (
    <nav className="navbar">
      {/* --- Website home link / brand area --- */}
      <NavLink to="/" className="logo-link">
        <img src={logoImg} alt="Sweet Box logo" className="navbar-logo" />
        <span>Sweet Box • Home</span>
      </NavLink>

      {/* --- Main page navigation --- */}
      <div className="links">
        {navigationLinks.map((link) => (
          <NavLink key={link.path} to={link.path} className={getNavLinkClass}>
            {link.label}
          </NavLink>
        ))}

        {/* --- Checkout link shows a visual indicator when the basket has items --- */}
        <NavLink to="/checkout" className={getNavLinkClass}>
          Checkout
          {basketCount > 0 && <span className="basket-dot"></span>}
        </NavLink>
      </div>
    </nav>
  );
}

export default Navbar;
